### ISSUE TITLE
Developing Navbar

### ISSUE THREAD

**Issue by MoazamAli45** [MoazamAli45/Quiz-AppHactoberfest2024#10] opened 2024-10-16 19:18 UTC
Navbar should have home and about link.

**Comment by siddharthgoel94** [comment] 2024-10-16 19:29
Hi,
Can you please assign this issue to me

**Comment by MoazamAli45** [comment] 2024-10-16 19:33
Navbar should be according to design. Assigned

**Comment by siddharthgoel94** [comment] 2024-10-16 19:37
Thank You
Well by design you mean the existing theme of website?

**Comment by MoazamAli45** [comment] 2024-10-16 19:43
Yes

**Closed as completed** 2024-10-17 08:12 UTC
Labels: enhancement, good first issue, hacktoberfest-accepted
